-- Benny finance and AI personalization schema.
-- The Telegram bot is server-side and uses service_role; end-user roles get no access.

create table public.user_profiles (
    user_id text primary key,
    username text not null default '',
    first_name text not null default '',
    full_name text,
    nickname text,
    birthday date,
    timezone text not null default 'Asia/Bangkok',
    currency_code text not null default 'IDR' check (currency_code ~ '^[A-Z]{3}$'),
    last_active timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.transactions (
    id bigint generated by default as identity primary key,
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    operation_id text,
    date date not null,
    time time not null,
    item_name text not null check (btrim(item_name) <> ''),
    category text not null default 'Other',
    amount bigint not null check (amount > 0),
    location text not null default '',
    payment_method text not null default '',
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, operation_id),
    unique (id, user_id)
);

create table public.income (
    id bigint generated by default as identity primary key,
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    operation_id text,
    date date not null,
    time time not null,
    source text not null check (btrim(source) <> ''),
    category text not null default 'Income',
    amount bigint not null check (amount > 0),
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, operation_id)
);

create table public.chat_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    telegram_chat_id text not null,
    status text not null default 'active' check (status in ('active', 'closed')),
    started_at timestamptz not null default now(),
    ended_at timestamptz,
    last_message_at timestamptz not null default now(),
    summary text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (ended_at is null or ended_at >= started_at),
    unique (id, user_id)
);

create table public.chat_messages (
    id bigint generated by default as identity primary key,
    session_id uuid not null,
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    telegram_message_id bigint,
    role text not null check (role in ('user', 'assistant', 'system', 'tool')),
    content text not null,
    content_type text not null default 'text' check (content_type in ('text', 'voice', 'image', 'tool')),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    foreign key (session_id, user_id) references public.chat_sessions(id, user_id) on delete cascade,
    unique (session_id, telegram_message_id, role)
);

create table public.agent_harness (
    user_id text primary key references public.user_profiles(user_id) on delete cascade,
    preferred_name text,
    agent_name text not null default 'Benny',
    language_code text not null default 'id',
    tone text not null default 'friendly',
    roast_intensity smallint not null default 2 check (roast_intensity between 0 and 5),
    roast_enabled boolean not null default true,
    system_context text,
    personality jsonb not null default '{}'::jsonb,
    boundaries jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create table public.user_preferences (
    id bigint generated by default as identity primary key,
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    preference_key text not null check (preference_key ~ '^[a-z0-9_.-]+$'),
    preference_value jsonb not null,
    source text not null default 'explicit' check (source in ('explicit', 'inferred', 'imported')),
    confidence numeric(4,3) not null default 1 check (confidence between 0 and 1),
    is_active boolean not null default true,
    observed_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, preference_key)
);

create table public.spending_assessments (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null,
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    verdict text not null check (verdict in ('wise', 'unwise', 'uncertain')),
    reason text not null,
    confidence numeric(4,3) check (confidence between 0 and 1),
    assessed_by text not null default 'ai',
    model text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    foreign key (transaction_id, user_id) references public.transactions(id, user_id) on delete cascade,
    unique (transaction_id)
);

create table public.roast_runs (
    id uuid primary key default gen_random_uuid(),
    user_id text not null references public.user_profiles(user_id) on delete cascade,
    session_id uuid,
    period_start date not null,
    period_end date not null,
    total_income bigint not null default 0 check (total_income >= 0),
    total_expense bigint not null default 0 check (total_expense >= 0),
    unwise_expense bigint not null default 0 check (unwise_expense >= 0),
    roast_text text not null check (btrim(roast_text) <> ''),
    severity smallint not null default 2 check (severity between 0 and 5),
    model text,
    input_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    foreign key (session_id, user_id) references public.chat_sessions(id, user_id) on delete set null (session_id),
    check (period_end >= period_start),
    check (unwise_expense <= total_expense)
);

create index transactions_user_date_idx on public.transactions (user_id, date desc, time desc);
create index transactions_user_category_date_idx on public.transactions (user_id, category, date desc);
create index income_user_date_idx on public.income (user_id, date desc, time desc);
create index chat_sessions_user_last_message_idx on public.chat_sessions (user_id, last_message_at desc);
create unique index chat_sessions_one_active_idx on public.chat_sessions (user_id, telegram_chat_id) where status = 'active';
create index chat_messages_session_created_idx on public.chat_messages (session_id, created_at);
create index chat_messages_user_created_idx on public.chat_messages (user_id, created_at desc);
create index chat_messages_session_user_fk_idx on public.chat_messages (session_id, user_id);
create index user_preferences_active_idx on public.user_preferences (user_id, preference_key) where is_active;
create index spending_assessments_unwise_idx on public.spending_assessments (user_id, created_at desc) where verdict = 'unwise';
create index spending_assessments_transaction_user_fk_idx on public.spending_assessments (transaction_id, user_id);
create index roast_runs_user_period_idx on public.roast_runs (user_id, period_end desc);
create index roast_runs_session_user_fk_idx on public.roast_runs (session_id, user_id);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger user_profiles_set_updated_at before update on public.user_profiles
for each row execute function public.set_updated_at();
create trigger transactions_set_updated_at before update on public.transactions
for each row execute function public.set_updated_at();
create trigger income_set_updated_at before update on public.income
for each row execute function public.set_updated_at();
create trigger chat_sessions_set_updated_at before update on public.chat_sessions
for each row execute function public.set_updated_at();
create trigger agent_harness_set_updated_at before update on public.agent_harness
for each row execute function public.set_updated_at();
create trigger user_preferences_set_updated_at before update on public.user_preferences
for each row execute function public.set_updated_at();
create trigger spending_assessments_set_updated_at before update on public.spending_assessments
for each row execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.transactions enable row level security;
alter table public.income enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.agent_harness enable row level security;
alter table public.user_preferences enable row level security;
alter table public.spending_assessments enable row level security;
alter table public.roast_runs enable row level security;

revoke all on table public.user_profiles, public.transactions, public.income,
    public.chat_sessions, public.chat_messages, public.agent_harness,
    public.user_preferences, public.spending_assessments, public.roast_runs
from anon, authenticated;
grant select, insert, update, delete on table public.user_profiles, public.transactions,
    public.income, public.chat_sessions, public.chat_messages, public.agent_harness,
    public.user_preferences, public.spending_assessments, public.roast_runs
to service_role;
grant usage, select on all sequences in schema public to service_role;
revoke all on function public.set_updated_at() from public, anon, authenticated;
